apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault-test.vault.svc:8200"
        vault.security.banzaicloud.io/vault-role: "myapp" 
        vault.security.banzaicloud.io/vault-path: "kubernetes" 
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp
      containers:
      - image: docker.io/sespindola/prueba-vswh:1.0.1
        name: app
        resources: {}
        env: 
        - name: APP_USER
          value: vault:secret/data/myapp#USER
        - name: APP_PASSWORD
          value: vault:secret/data/myapp#PASSWORD
          
